images:
- 'gcr.io/bgdestroyer/bgdestroyer-worker'

steps:
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://bgdestroyer/u2net.onnx', '/workspace/']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/bgdestroyer/bgdestroyer-worker', '.' ]
  env:
  - "DOCKER_BUILDKIT=1"
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/bgdestroyer/bgdestroyer-worker']
  env:
  - "DOCKER_BUILDKIT=1"
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['beta', 'run', 'deploy', 'bg-remover', '--image', 'gcr.io/bgdestroyer/bgdestroyer-worker',
         '--region', 'us-central1', '--cpu=1', '--memory=2Gi', '--max-instances=10', '--allow-unauthenticated',
         '--concurrency=5', '--set-secrets=REDIS_HOST=redis-host:1,REDIS_PASSWORD=redis-password:1',
         '--execution-environment=gen2', '--min-instances=0']
