version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      - ./bgdestroyer.json:/tmp/keys/keyfile.json:ro
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
